version: '3'

services:
  nginx:
    build:
      context: ./nginx
    image: nginx_i
    container_name: nginx_c
    ports:
      - "8888:8080"
    volumes:
      - ./dist:/wwwroot:ro
  webpack:
    build:
      context: .
    image: webpack_i
    container_name: webpack_c
    volumes:
      - ./src:/src:ro
      - ./dist:/dist:z