version: '3'

services:
  webpack:
    container_name: react_admin
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
