version: '3'

services:
  nginx:
    build:
      context: ./nginx
    image: reactjs_nginx
    container_name: reactjs_nginx_container
    ports:
      - "80:8080"
    volumes:
      - ./dist:/wwwroot:ro
  webpack:
    build:
      context: ./webpack
    image: reactjs_webpack
    container_name: reactjs_webpack_container
    volumes:
      - ./src:/src:ro
      - ./dist:/dist:z

#  elasticsearch:
#    image: elasticsearch
#    container_name: elasticsearch